#include "blocks_generated.h"
#include <stddef.h>

// This file is generated by tools/gen_blocks_with_faces.py. Do not edit directly.
/*
Missing 69 blocks:
    0 air                            Air
    8 flowing_water                  Water
    9 water                          Stationary Water
   10 flowing_lava                   Lava
   11 lava                           Stationary Lava
   27 golden_rail                    Powered Rail
   28 detector_rail                  Detector Rail
   50 torch                          Torch
   51 fire                           Fire
   54 chest                          Chest
   59 wheat                          Wheat
   63 standing_sign                  Standing Sign
   65 ladder                         Ladder
   66 rail                           Rail
   68 wall_sign                      Wall Sign
   69 lever                          Lever
   70 stone_pressure_plate           Stone Pressure Plate
   72 wooden_pressure_plate          Wooden Pressure Plate
   75 unlit_redstone_torch           Redstone Torch (inactive)
   76 redstone_torch                 Redstone Torch (active)
   77 stone_button                   Stone Button
   78 snow_layer                     Snow (layer)
   85 fence                          Fence
   90 portal                         Nether Portal
   96 trapdoor                       Trapdoor
   97 monster_egg                    Monster Egg
  101 iron_bars                      Iron Bars
  102 glass_pane                     Glass Pane
  104 pumpkin_stem                   Pumpkin Stem
  105 melon_stem                     Melon Stem
  106 vine                           Vines
  107 fence_gate                     Fence Gate
  111 waterlily                      Lily Pad
  113 nether_brick_fence             Nether Brick Fence
  115 nether_wart                    Nether Wart
  117 brewing_stand                  Brewing Stand
  119 end_portal                     End Portal
  127 cocoa                          Cocoa
  130 ender_chest                    Ender Chest
  131 tripwire_hook                  Tripwire Hook
  132 tripwire                       Tripwire
  138 beacon                         Beacon
  139 cobblestone_wall               Cobblestone Wall
  140 flower_pot                     Flower Pot
  141 carrots                        Carrot
  142 potatoes                       Potato
  143 wooden_button                  Wooden Button
  144 skull                          Mob head
  146 trapped_chest                  Trapped Chest
  147 light_weighted_pressure_plate  Weighted Pressure Plate (Light)
  148 heavy_weighted_pressure_plate  Weighted Pressure Plate (Heavy)
  157 activator_rail                 Activator Rail
  160 stained_glass_pane             Stained Glass Pane
  165 slime                          Slime Block
  166 barrier                        Barrier
  167 iron_trapdoor                  Iron Trapdoor
  171 carpet                         Carpet
  176 standing_banner                Standing Banner
  177 wall_banner                    Wall Banner
  183 spruce_fence_gate              Spruce Fence Gate
  184 birch_fence_gate               Birch Fence Gate
  185 jungle_fence_gate              Jungle Fence Gate
  186 dark_oak_fence_gate            Dark Oak Fence Gate
  187 acacia_fence_gate              Acacia Fence Gate
  188 spruce_fence                   Spruce Fence
  189 birch_fence                    Birch Fence
  190 jungle_fence                   Jungle Fence
  191 dark_oak_fence                 Dark Oak Fence
  192 acacia_fence                   Acacia Fence

These all have custom models contained in blocks_models.json, skipping for now

*/ 
const BlockTextures* get_block_textures(uint16_t id, uint8_t meta) {
    switch(id) {

    case 0: { // Air
        (void)meta;
        return NULL; // No model found
    }

    case 1: { // Stone
        // Variants:
        //   meta 0: Stone
        //   meta 1: Granite
        //   meta 2: Polished Granite
        //   meta 3: Diorite
        //   meta 4: Polished Diorite
        //   meta 5: Andesite
        //   meta 6: Polished Andesite
        (void)meta;
        static const BlockTextures tex = {
            .top = tex_stone,
            .bottom = tex_stone,
            .north = tex_stone,
            .south = tex_stone,
            .east = tex_stone,
            .west = tex_stone,
        };
        return &tex;
    }

    case 2: { // Grass Block
        (void)meta;
        static const BlockTextures tex = {
            .top = tex_grass_top,
            .bottom = tex_dirt,
            .north = tex_grass_side,
            .south = tex_grass_side,
            .east = tex_grass_side,
            .west = tex_grass_side,
        };
        return &tex;
    }

    case 3: { // Dirt
        // Variants:
        //   meta 0: Dirt
        //   meta 1: Coarse Dirt
        //   meta 2: Podzol
        (void)meta;
        static const BlockTextures tex = {
            .top = tex_dirt,
            .bottom = tex_dirt,
            .north = tex_dirt,
            .south = tex_dirt,
            .east = tex_dirt,
            .west = tex_dirt,
        };
        return &tex;
    }

    case 4: { // Cobblestone
        (void)meta;
        static const BlockTextures tex = {
            .top = tex_cobblestone,
            .bottom = tex_cobblestone,
            .north = tex_cobblestone,
            .south = tex_cobblestone,
            .east = tex_cobblestone,
            .west = tex_cobblestone,
        };
        return &tex;
    }

    case 5: { // Wood Planks
        // Variants:
        //   meta 0: Oak Wood Planks
        //   meta 1: Spruce Wood Planks
        //   meta 2: Birch Wood Planks
        //   meta 3: Jungle Wood Planks
        //   meta 4: Acacia Wood Planks
        //   meta 5: Dark Oak Wood Planks
        (void)meta;
        static const BlockTextures tex = {
            .top = tex_planks_oak,
            .bottom = tex_planks_oak,
            .north = tex_planks_oak,
            .south = tex_planks_oak,
            .east = tex_planks_oak,
            .west = tex_planks_oak,
        };
        return &tex;
    }

    case 6: { // Sapling
        (void)meta;
        static const BlockTextures tex = {
            .top = tex_sapling_oak,
            .bottom = tex_sapling_oak,
            .north = tex_sapling_oak,
            .south = tex_sapling_oak,
            .east = tex_sapling_oak,
            .west = tex_sapling_oak,
        };
        return &tex;
    }

    case 7: { // Bedrock
        (void)meta;
        static const BlockTextures tex = {
            .top = tex_bedrock,
            .bottom = tex_bedrock,
            .north = tex_bedrock,
            .south = tex_bedrock,
            .east = tex_bedrock,
            .west = tex_bedrock,
        };
        return &tex;
    }

    case 8: { // Water
        (void)meta;
        return NULL; // No model found
    }

    case 9: { // Stationary Water
        (void)meta;
        return NULL; // No model found
    }

    case 10: { // Lava
        (void)meta;
        return NULL; // No model found
    }

    case 11: { // Stationary Lava
        (void)meta;
        return NULL; // No model found
    }

    case 12: { // Sand
        // Variants:
        //   meta 0: Sand
        //   meta 1: Red sand
        (void)meta;
        static const BlockTextures tex = {
            .top = tex_sand,
            .bottom = tex_sand,
            .north = tex_sand,
            .south = tex_sand,
            .east = tex_sand,
            .west = tex_sand,
        };
        return &tex;
    }

    case 13: { // Gravel
        (void)meta;
        static const BlockTextures tex = {
            .top = tex_gravel,
            .bottom = tex_gravel,
            .north = tex_gravel,
            .south = tex_gravel,
            .east = tex_gravel,
            .west = tex_gravel,
        };
        return &tex;
    }

    case 14: { // Gold Ore
        (void)meta;
        static const BlockTextures tex = {
            .top = tex_gold_ore,
            .bottom = tex_gold_ore,
            .north = tex_gold_ore,
            .south = tex_gold_ore,
            .east = tex_gold_ore,
            .west = tex_gold_ore,
        };
        return &tex;
    }

    case 15: { // Iron Ore
        (void)meta;
        static const BlockTextures tex = {
            .top = tex_iron_ore,
            .bottom = tex_iron_ore,
            .north = tex_iron_ore,
            .south = tex_iron_ore,
            .east = tex_iron_ore,
            .west = tex_iron_ore,
        };
        return &tex;
    }

    case 16: { // Coal Ore
        (void)meta;
        static const BlockTextures tex = {
            .top = tex_coal_ore,
            .bottom = tex_coal_ore,
            .north = tex_coal_ore,
            .south = tex_coal_ore,
            .east = tex_coal_ore,
            .west = tex_coal_ore,
        };
        return &tex;
    }

    case 17: { // Wood
        // Variants:
        //   meta 0: Oak wood facing up/down
        //   meta 1: Spruce wood facing up/down
        //   meta 2: Birch wood facing up/down
        //   meta 3: Jungle wood facing up/down
        //   meta 4: Oak wood facing East/West
        //   meta 5: Spruce wood facing East/West
        //   meta 6: Birch wood facing East/West
        //   meta 7: Jungle wood facing East/West
        //   meta 8: Oak wood facing North/South
        //   meta 9: Spruce wood facing North/South
        //   meta 10: Birch wood facing North/South
        //   meta 11: Jungle wood facing North/South
        //   meta 12: Oak wood with only bark
        //   meta 13: Spruce wood with only bark
        //   meta 14: Birch wood with only bark
        //   meta 15: Jungle wood with only bark
        (void)meta;
        static const BlockTextures tex = {
            .top = tex_log_oak_top,
            .bottom = tex_log_oak_top,
            .north = tex_log_oak,
            .south = tex_log_oak,
            .east = tex_log_oak,
            .west = tex_log_oak,
        };
        return &tex;
    }

    case 18: { // Leaves
        // Variants:
        //   meta 0: Oak Leaves
        //   meta 1: Spruce Leaves
        //   meta 2: Birch Leaves
        //   meta 3: Jungle Leaves
        //   meta 4: Oak Leaves (no decay)
        //   meta 5: Spruce Leaves (no decay)
        //   meta 6: Birch Leaves (no decay)
        //   meta 7: Jungle Leaves (no decay)
        //   meta 8: Oak Leaves (check decay)
        //   meta 9: Spruce Leaves (check decay)
        //   meta 10: Birch Leaves (check decay)
        //   meta 11: Jungle Leaves (check decay)
        //   meta 12: Oak Leaves (no decay and check decay)
        //   meta 13: Spruce Leaves (no decay and check decay)
        //   meta 14: Birch Leaves (no decay and check decay)
        //   meta 15: Jungle Leaves (no decay and check decay)
        (void)meta;
        static const BlockTextures tex = {
            .top = tex_leaves_oak,
            .bottom = tex_leaves_oak,
            .north = tex_leaves_oak,
            .south = tex_leaves_oak,
            .east = tex_leaves_oak,
            .west = tex_leaves_oak,
        };
        return &tex;
    }

    case 19: { // Sponge
        // Variants:
        //   meta 0: Sponge
        //   meta 1: Wet Sponge
        (void)meta;
        static const BlockTextures tex = {
            .top = tex_sponge,
            .bottom = tex_sponge,
            .north = tex_sponge,
            .south = tex_sponge,
            .east = tex_sponge,
            .west = tex_sponge,
        };
        return &tex;
    }

    case 20: { // Glass
        (void)meta;
        static const BlockTextures tex = {
            .top = tex_glass,
            .bottom = tex_glass,
            .north = tex_glass,
            .south = tex_glass,
            .east = tex_glass,
            .west = tex_glass,
        };
        return &tex;
    }

    case 21: { // Lapis Lazuli Ore
        (void)meta;
        static const BlockTextures tex = {
            .top = tex_lapis_ore,
            .bottom = tex_lapis_ore,
            .north = tex_lapis_ore,
            .south = tex_lapis_ore,
            .east = tex_lapis_ore,
            .west = tex_lapis_ore,
        };
        return &tex;
    }

    case 22: { // Lapis Lazuli Block
        (void)meta;
        static const BlockTextures tex = {
            .top = tex_lapis_block,
            .bottom = tex_lapis_block,
            .north = tex_lapis_block,
            .south = tex_lapis_block,
            .east = tex_lapis_block,
            .west = tex_lapis_block,
        };
        return &tex;
    }

    case 23: { // Dispenser
        (void)meta;
        static const BlockTextures tex = {
            .top = NULL,
            .bottom = NULL,
            .north = tex_dispenser_front_vertical,
            .south = tex_furnace_top,
            .east = tex_furnace_top,
            .west = tex_furnace_top,
        };
        return &tex;
    }

    case 24: { // Sandstone
        // Variants:
        //   meta 0: Sandstone
        //   meta 1: Chiseled sandstone
        //   meta 2: Smooth sandstone
        (void)meta;
        static const BlockTextures tex = {
            .top = tex_sandstone_top,
            .bottom = tex_sandstone_bottom,
            .north = tex_sandstone_normal,
            .south = tex_sandstone_normal,
            .east = tex_sandstone_normal,
            .west = tex_sandstone_normal,
        };
        return &tex;
    }

    case 25: { // Note Block
        (void)meta;
        static const BlockTextures tex = {
            .top = tex_noteblock,
            .bottom = tex_noteblock,
            .north = tex_noteblock,
            .south = tex_noteblock,
            .east = tex_noteblock,
            .west = tex_noteblock,
        };
        return &tex;
    }

    case 26: { // Bed
        (void)meta;
        static const BlockTextures tex = {
            .top = tex_bed_feet_end,
            .bottom = tex_bed_feet_end,
            .north = tex_bed_feet_side,
            .south = tex_bed_feet_side,
            .east = tex_bed_feet_side,
            .west = tex_bed_feet_side,
        };
        return &tex;
    }

    case 27: { // Powered Rail
        (void)meta;
        return NULL; // No model found
    }

    case 28: { // Detector Rail
        (void)meta;
        return NULL; // No model found
    }

    case 29: { // Sticky Piston
        (void)meta;
        static const BlockTextures tex = {
            .top = NULL,
            .bottom = tex_piston_bottom,
            .north = tex_piston_side,
            .south = tex_piston_side,
            .east = tex_piston_side,
            .west = tex_piston_side,
        };
        return &tex;
    }

    case 30: { // Cobweb
        (void)meta;
        static const BlockTextures tex = {
            .top = tex_web,
            .bottom = tex_web,
            .north = tex_web,
            .south = tex_web,
            .east = tex_web,
            .west = tex_web,
        };
        return &tex;
    }

    case 31: { // Grass
        // Variants:
        //   meta 0: Shrub
        //   meta 1: Tall Grass
        //   meta 2: Fern
        (void)meta;
        static const BlockTextures tex = {
            .top = tex_tallgrass,
            .bottom = tex_tallgrass,
            .north = tex_tallgrass,
            .south = tex_tallgrass,
            .east = tex_tallgrass,
            .west = tex_tallgrass,
        };
        return &tex;
    }

    case 32: { // Dead Bush
        (void)meta;
        static const BlockTextures tex = {
            .top = tex_deadbush,
            .bottom = tex_deadbush,
            .north = tex_deadbush,
            .south = tex_deadbush,
            .east = tex_deadbush,
            .west = tex_deadbush,
        };
        return &tex;
    }

    case 33: { // Piston
        (void)meta;
        static const BlockTextures tex = {
            .top = NULL,
            .bottom = tex_piston_bottom,
            .north = tex_piston_side,
            .south = tex_piston_side,
            .east = tex_piston_side,
            .west = tex_piston_side,
        };
        return &tex;
    }

    case 34: { // Piston Head
        (void)meta;
        static const BlockTextures tex = {
            .top = NULL,
            .bottom = NULL,
            .north = tex_piston_side,
            .south = tex_piston_side,
            .east = tex_piston_side,
            .west = tex_piston_side,
        };
        return &tex;
    }

    case 35: { // Wool
        // Variants:
        //   meta 0: White Wool
        //   meta 1: Orange Wool
        //   meta 2: Magenta Wool
        //   meta 3: Light blue Wool
        //   meta 4: Yellow Wool
        //   meta 5: Lime Wool
        //   meta 6: Pink Wool
        //   meta 7: Gray Wool
        //   meta 8: Light gray Wool
        //   meta 9: Cyan Wool
        //   meta 10: Purple Wool
        //   meta 11: Blue Wool
        //   meta 12: Brown Wool
        //   meta 13: Green Wool
        //   meta 14: Red Wool
        //   meta 15: Black Wool
        (void)meta;
        static const BlockTextures tex = {
            .top = tex_wool_colored_white,
            .bottom = tex_wool_colored_white,
            .north = tex_wool_colored_white,
            .south = tex_wool_colored_white,
            .east = tex_wool_colored_white,
            .west = tex_wool_colored_white,
        };
        return &tex;
    }

    case 36: { // Block moved by Piston
        (void)meta;
        static const BlockTextures tex = {
            .top = NULL,
            .bottom = tex_piston_bottom,
            .north = tex_piston_side,
            .south = tex_piston_side,
            .east = tex_piston_side,
            .west = tex_piston_side,
        };
        return &tex;
    }

    case 37: { // Dandelion
        (void)meta;
        static const BlockTextures tex = {
            .top = tex_flower_dandelion,
            .bottom = tex_flower_dandelion,
            .north = tex_flower_dandelion,
            .south = tex_flower_dandelion,
            .east = tex_flower_dandelion,
            .west = tex_flower_dandelion,
        };
        return &tex;
    }

    case 38: { // Poppy
        // Variants:
        //   meta 0: Poppy
        //   meta 1: Blue Orchid
        //   meta 2: Allium
        //   meta 3: Azure Bluet
        //   meta 4: Red Tulip
        //   meta 5: Orange Tulip
        //   meta 6: White Tulip
        //   meta 7: Pink Tulip
        //   meta 8: Oxeye Daisy
        (void)meta;
        static const BlockTextures tex = {
            .top = tex_flower_rose,
            .bottom = tex_flower_rose,
            .north = tex_flower_rose,
            .south = tex_flower_rose,
            .east = tex_flower_rose,
            .west = tex_flower_rose,
        };
        return &tex;
    }

    case 39: { // Brown Mushroom
        (void)meta;
        static const BlockTextures tex = {
            .top = tex_mushroom_brown,
            .bottom = tex_mushroom_brown,
            .north = tex_mushroom_brown,
            .south = tex_mushroom_brown,
            .east = tex_mushroom_brown,
            .west = tex_mushroom_brown,
        };
        return &tex;
    }

    case 40: { // Red Mushroom
        (void)meta;
        static const BlockTextures tex = {
            .top = tex_mushroom_red,
            .bottom = tex_mushroom_red,
            .north = tex_mushroom_red,
            .south = tex_mushroom_red,
            .east = tex_mushroom_red,
            .west = tex_mushroom_red,
        };
        return &tex;
    }

    case 41: { // Block of Gold
        (void)meta;
        static const BlockTextures tex = {
            .top = tex_gold_block,
            .bottom = tex_gold_block,
            .north = tex_gold_block,
            .south = tex_gold_block,
            .east = tex_gold_block,
            .west = tex_gold_block,
        };
        return &tex;
    }

    case 42: { // Block of Iron
        (void)meta;
        static const BlockTextures tex = {
            .top = tex_iron_block,
            .bottom = tex_iron_block,
            .north = tex_iron_block,
            .south = tex_iron_block,
            .east = tex_iron_block,
            .west = tex_iron_block,
        };
        return &tex;
    }

    case 43: { // Double Stone Slab
        // Variants:
        //   meta 0: Double Stone Slab
        //   meta 1: Double Sandstone Slab
        //   meta 2: Double (Stone) Wooden Slab
        //   meta 3: Double Cobblestone Slab
        //   meta 4: Double Bricks Slab
        //   meta 5: Double Stone Brick Slab
        //   meta 6: Double Nether Brick Slab
        //   meta 7: Double Quartz Slab
        //   meta 8: Smooth Double Stone Slab
        //   meta 9: Smooth Double Sandstone Slab
        //   meta 15: Tile Double Quartz Slab (note the underside)
        (void)meta;
        static const BlockTextures tex = {
            .top = tex_stone_slab_top,
            .bottom = tex_stone_slab_top,
            .north = tex_stone_slab_side,
            .south = tex_stone_slab_side,
            .east = tex_stone_slab_side,
            .west = tex_stone_slab_side,
        };
        return &tex;
    }

    case 44: { // Stone Slab
        // Variants:
        //   meta 0: Stone Slab
        //   meta 1: Sandstone Slab
        //   meta 2: (Stone) Wooden Slab
        //   meta 3: Cobblestone Slab
        //   meta 4: Bricks Slab
        //   meta 5: Stone Brick Slab
        //   meta 6: Nether Brick Slab
        //   meta 7: Quartz Slab
        //   meta 8: Upper Stone Slab
        //   meta 9: Upper Sandstone Slab
        //   meta 10: Upper (Stone) Wooden Slab
        //   meta 11: Upper Cobblestone Slab
        //   meta 12: Upper Bricks Slab
        //   meta 13: Upper Stone Brick Slab
        //   meta 14: Upper Nether Brick Slab
        //   meta 15: Upper Quartz Slab
        (void)meta;
        static const BlockTextures tex = {
            .top = tex_stone_slab_top,
            .bottom = tex_stone_slab_top,
            .north = tex_stone_slab_side,
            .south = tex_stone_slab_side,
            .east = tex_stone_slab_side,
            .west = tex_stone_slab_side,
        };
        return &tex;
    }

    case 45: { // Bricks
        (void)meta;
        static const BlockTextures tex = {
            .top = tex_brick,
            .bottom = tex_brick,
            .north = tex_brick,
            .south = tex_brick,
            .east = tex_brick,
            .west = tex_brick,
        };
        return &tex;
    }

    case 46: { // TNT
        // Variants:
        //   meta 0: Drops a TNT item when broken
        //   meta 1: Activates when broken
        (void)meta;
        static const BlockTextures tex = {
            .top = tex_tnt_top,
            .bottom = tex_tnt_bottom,
            .north = tex_tnt_side,
            .south = tex_tnt_side,
            .east = tex_tnt_side,
            .west = tex_tnt_side,
        };
        return &tex;
    }

    case 47: { // Bookshelf
        (void)meta;
        static const BlockTextures tex = {
            .top = tex_planks_oak,
            .bottom = tex_planks_oak,
            .north = tex_bookshelf,
            .south = tex_bookshelf,
            .east = tex_bookshelf,
            .west = tex_bookshelf,
        };
        return &tex;
    }

    case 48: { // Moss Stone
        (void)meta;
        static const BlockTextures tex = {
            .top = tex_cobblestone_mossy,
            .bottom = tex_cobblestone_mossy,
            .north = tex_cobblestone_mossy,
            .south = tex_cobblestone_mossy,
            .east = tex_cobblestone_mossy,
            .west = tex_cobblestone_mossy,
        };
        return &tex;
    }

    case 49: { // Obsidian
        (void)meta;
        static const BlockTextures tex = {
            .top = tex_obsidian,
            .bottom = tex_obsidian,
            .north = tex_obsidian,
            .south = tex_obsidian,
            .east = tex_obsidian,
            .west = tex_obsidian,
        };
        return &tex;
    }

    case 50: { // Torch
        // Variants:
        //   meta 0: Torch facing east (attached to a block to its west)
        //   meta 1: Torch facing west (attached to a block to its east)
        //   meta 2: Torch facing south (attached to a block to its north)
        //   meta 3: Torch facing north (attached to a block to its south)
        //   meta 4: Torch facing up (attached to a block beneath it)
        (void)meta;
        return NULL; // No model found
    }

    case 51: { // Fire
        (void)meta;
        return NULL; // No model found
    }

    case 52: { // Monster Spawner
        (void)meta;
        static const BlockTextures tex = {
            .top = tex_mob_spawner,
            .bottom = tex_mob_spawner,
            .north = tex_mob_spawner,
            .south = tex_mob_spawner,
            .east = tex_mob_spawner,
            .west = tex_mob_spawner,
        };
        return &tex;
    }

    case 53: { // Oak Wood Stairs
        (void)meta;
        static const BlockTextures tex = {
            .top = tex_planks_oak,
            .bottom = tex_planks_oak,
            .north = tex_planks_oak,
            .south = tex_planks_oak,
            .east = tex_planks_oak,
            .west = tex_planks_oak,
        };
        return &tex;
    }

    case 54: { // Chest
        (void)meta;
        return NULL; // No model found
    }

    case 55: { // Redstone Wire
        (void)meta;
        static const BlockTextures tex = {
            .top = tex_redstone_dust_cross,
            .bottom = tex_redstone_dust_cross,
            .north = tex_redstone_dust_cross,
            .south = tex_redstone_dust_cross,
            .east = tex_redstone_dust_cross,
            .west = tex_redstone_dust_cross,
        };
        return &tex;
    }

    case 56: { // Diamond Ore
        (void)meta;
        static const BlockTextures tex = {
            .top = tex_diamond_ore,
            .bottom = tex_diamond_ore,
            .north = tex_diamond_ore,
            .south = tex_diamond_ore,
            .east = tex_diamond_ore,
            .west = tex_diamond_ore,
        };
        return &tex;
    }

    case 57: { // Block of Diamond
        (void)meta;
        static const BlockTextures tex = {
            .top = tex_diamond_block,
            .bottom = tex_diamond_block,
            .north = tex_diamond_block,
            .south = tex_diamond_block,
            .east = tex_diamond_block,
            .west = tex_diamond_block,
        };
        return &tex;
    }

    case 58: { // Crafting Table
        (void)meta;
        static const BlockTextures tex = {
            .top = NULL,
            .bottom = NULL,
            .north = tex_crafting_table_front,
            .south = tex_crafting_table_side,
            .east = tex_crafting_table_side,
            .west = tex_crafting_table_front,
        };
        return &tex;
    }

    case 59: { // Wheat
        (void)meta;
        return NULL; // No model found
    }

    case 60: { // Farmland
        (void)meta;
        static const BlockTextures tex = {
            .top = tex_farmland_dry,
            .bottom = NULL,
            .north = NULL,
            .south = NULL,
            .east = NULL,
            .west = NULL,
        };
        return &tex;
    }

    case 61: { // Furnace
        (void)meta;
        static const BlockTextures tex = {
            .top = tex_furnace_top,
            .bottom = NULL,
            .north = tex_furnace_front_off,
            .south = tex_furnace_side,
            .east = tex_furnace_side,
            .west = tex_furnace_side,
        };
        return &tex;
    }

    case 62: { // Burning Furnace
        (void)meta;
        static const BlockTextures tex = {
            .top = tex_furnace_top,
            .bottom = NULL,
            .north = tex_furnace_front_on,
            .south = tex_furnace_side,
            .east = tex_furnace_side,
            .west = tex_furnace_side,
        };
        return &tex;
    }

    case 63: { // Standing Sign
        (void)meta;
        return NULL; // No model found
    }

    case 64: { // Oak Door
        (void)meta;
        static const BlockTextures tex = {
            .top = tex_door_wood_upper,
            .bottom = tex_door_wood_lower,
            .north = NULL,
            .south = NULL,
            .east = NULL,
            .west = NULL,
        };
        return &tex;
    }

    case 65: { // Ladder
        (void)meta;
        return NULL; // No model found
    }

    case 66: { // Rail
        (void)meta;
        return NULL; // No model found
    }

    case 67: { // Cobblestone Stairs
        (void)meta;
        static const BlockTextures tex = {
            .top = tex_cobblestone,
            .bottom = tex_cobblestone,
            .north = tex_cobblestone,
            .south = tex_cobblestone,
            .east = tex_cobblestone,
            .west = tex_cobblestone,
        };
        return &tex;
    }

    case 68: { // Wall Sign
        (void)meta;
        return NULL; // No model found
    }

    case 69: { // Lever
        (void)meta;
        return NULL; // No model found
    }

    case 70: { // Stone Pressure Plate
        (void)meta;
        return NULL; // No model found
    }

    case 71: { // Iron Door
        (void)meta;
        static const BlockTextures tex = {
            .top = tex_door_iron_upper,
            .bottom = tex_door_iron_lower,
            .north = NULL,
            .south = NULL,
            .east = NULL,
            .west = NULL,
        };
        return &tex;
    }

    case 72: { // Wooden Pressure Plate
        (void)meta;
        return NULL; // No model found
    }

    case 73: { // Redstone Ore
        (void)meta;
        static const BlockTextures tex = {
            .top = tex_redstone_ore,
            .bottom = tex_redstone_ore,
            .north = tex_redstone_ore,
            .south = tex_redstone_ore,
            .east = tex_redstone_ore,
            .west = tex_redstone_ore,
        };
        return &tex;
    }

    case 74: { // Glowing Redstone Ore
        (void)meta;
        static const BlockTextures tex = {
            .top = tex_redstone_ore,
            .bottom = tex_redstone_ore,
            .north = tex_redstone_ore,
            .south = tex_redstone_ore,
            .east = tex_redstone_ore,
            .west = tex_redstone_ore,
        };
        return &tex;
    }

    case 75: { // Redstone Torch (inactive)
        // Variants:
        //   meta 0: Redstone Torch (inactive) facing east (attached to a block to its west)
        //   meta 1: Redstone Torch (inactive) facing west (attached to a block to its east)
        //   meta 2: Redstone Torch (inactive) facing south (attached to a block to its north)
        //   meta 3: Redstone Torch (inactive) facing north (attached to a block to its south)
        //   meta 4: Redstone Torch (inactive) facing up (attached to a block beneath it)
        (void)meta;
        return NULL; // No model found
    }

    case 76: { // Redstone Torch (active)
        // Variants:
        //   meta 0: Redstone Torch (active) facing east (attached to a block to its west)
        //   meta 1: Redstone Torch (active) facing west (attached to a block to its east)
        //   meta 2: Redstone Torch (active) facing south (attached to a block to its north)
        //   meta 3: Redstone Torch (active) facing north (attached to a block to its south)
        //   meta 4: Redstone Torch (active) facing up (attached to a block beneath it)
        (void)meta;
        return NULL; // No model found
    }

    case 77: { // Stone Button
        (void)meta;
        return NULL; // No model found
    }

    case 78: { // Snow (layer)
        // Variants:
        //   meta 0: One layer, 2 pixels thick
        //   meta 1: Two layers, 4 pixels thick
        //   meta 2: Three layers, 6 pixels thick
        //   meta 3: Four layers, 8 pixels thick
        //   meta 4: Five layers, 10 pixels thick
        //   meta 5: Six layers, 12 pixels thick
        //   meta 6: Seven layers, 14 pixels thick
        //   meta 7: Eight layers, 16 pixels thick
        (void)meta;
        return NULL; // No model found
    }

    case 79: { // Ice
        (void)meta;
        static const BlockTextures tex = {
            .top = tex_ice,
            .bottom = tex_ice,
            .north = tex_ice,
            .south = tex_ice,
            .east = tex_ice,
            .west = tex_ice,
        };
        return &tex;
    }

    case 80: { // Snow
        (void)meta;
        static const BlockTextures tex = {
            .top = tex_snow,
            .bottom = tex_snow,
            .north = tex_snow,
            .south = tex_snow,
            .east = tex_snow,
            .west = tex_snow,
        };
        return &tex;
    }

    case 81: { // Cactus
        (void)meta;
        static const BlockTextures tex = {
            .top = tex_cactus_top,
            .bottom = tex_cactus_bottom,
            .north = tex_cactus_side,
            .south = tex_cactus_side,
            .east = tex_cactus_side,
            .west = tex_cactus_side,
        };
        return &tex;
    }

    case 82: { // Clay
        (void)meta;
        static const BlockTextures tex = {
            .top = tex_clay,
            .bottom = tex_clay,
            .north = tex_clay,
            .south = tex_clay,
            .east = tex_clay,
            .west = tex_clay,
        };
        return &tex;
    }

    case 83: { // Sugar Cane
        (void)meta;
        static const BlockTextures tex = {
            .top = tex_reeds,
            .bottom = tex_reeds,
            .north = tex_reeds,
            .south = tex_reeds,
            .east = tex_reeds,
            .west = tex_reeds,
        };
        return &tex;
    }

    case 84: { // Jukebox
        // Variants:
        //   meta 0: No disc inserted
        //   meta 1: Contains a disc
        (void)meta;
        static const BlockTextures tex = {
            .top = tex_jukebox_top,
            .bottom = NULL,
            .north = tex_jukebox_side,
            .south = tex_jukebox_side,
            .east = tex_jukebox_side,
            .west = tex_jukebox_side,
        };
        return &tex;
    }

    case 85: { // Fence
        (void)meta;
        return NULL; // No model found
    }

    case 86: { // Pumpkin
        (void)meta;
        static const BlockTextures tex = {
            .top = tex_pumpkin_top,
            .bottom = NULL,
            .north = tex_pumpkin_face_off,
            .south = tex_pumpkin_side,
            .east = tex_pumpkin_side,
            .west = tex_pumpkin_side,
        };
        return &tex;
    }

    case 87: { // Netherrack
        (void)meta;
        static const BlockTextures tex = {
            .top = tex_netherrack,
            .bottom = tex_netherrack,
            .north = tex_netherrack,
            .south = tex_netherrack,
            .east = tex_netherrack,
            .west = tex_netherrack,
        };
        return &tex;
    }

    case 88: { // Soul Sand
        (void)meta;
        static const BlockTextures tex = {
            .top = tex_soul_sand,
            .bottom = tex_soul_sand,
            .north = tex_soul_sand,
            .south = tex_soul_sand,
            .east = tex_soul_sand,
            .west = tex_soul_sand,
        };
        return &tex;
    }

    case 89: { // Glowstone
        (void)meta;
        static const BlockTextures tex = {
            .top = tex_glowstone,
            .bottom = tex_glowstone,
            .north = tex_glowstone,
            .south = tex_glowstone,
            .east = tex_glowstone,
            .west = tex_glowstone,
        };
        return &tex;
    }

    case 90: { // Nether Portal
        (void)meta;
        return NULL; // No model found
    }

    case 91: { // Jack o'Lantern
        (void)meta;
        static const BlockTextures tex = {
            .top = tex_pumpkin_top,
            .bottom = NULL,
            .north = tex_pumpkin_face_on,
            .south = tex_pumpkin_side,
            .east = tex_pumpkin_side,
            .west = tex_pumpkin_side,
        };
        return &tex;
    }

    case 92: { // Cake
        (void)meta;
        static const BlockTextures tex = {
            .top = tex_cake_top,
            .bottom = tex_cake_bottom,
            .north = tex_cake_side,
            .south = tex_cake_side,
            .east = tex_cake_side,
            .west = tex_cake_side,
        };
        return &tex;
    }

    case 93: { // Redstone Repeater (inactive)
        (void)meta;
        static const BlockTextures tex = {
            .top = tex_repeater_off,
            .bottom = NULL,
            .north = NULL,
            .south = NULL,
            .east = NULL,
            .west = NULL,
        };
        return &tex;
    }

    case 94: { // Redstone Repeater (active)
        (void)meta;
        static const BlockTextures tex = {
            .top = tex_repeater_on,
            .bottom = NULL,
            .north = NULL,
            .south = NULL,
            .east = NULL,
            .west = NULL,
        };
        return &tex;
    }

    case 95: { // Stained Glass
        (void)meta;
        static const BlockTextures tex = {
            .top = tex_glass_white,
            .bottom = tex_glass_white,
            .north = tex_glass_white,
            .south = tex_glass_white,
            .east = tex_glass_white,
            .west = tex_glass_white,
        };
        return &tex;
    }

    case 96: { // Trapdoor
        (void)meta;
        return NULL; // No model found
    }

    case 97: { // Monster Egg
        // Variants:
        //   meta 0: Stone Monster Egg
        //   meta 1: Cobblestone Monster Egg
        //   meta 2: Stone Brick Monster Egg
        //   meta 3: Mossy Stone Brick Monster Egg
        //   meta 4: Cracked Stone Brick Monster Egg
        //   meta 5: Chiseled Stone Brick Monster Egg
        (void)meta;
        return NULL; // No model found
    }

    case 98: { // Stone Bricks
        // Variants:
        //   meta 0: Stone brick
        //   meta 1: Mossy stone brick
        //   meta 2: Cracked stone brick
        //   meta 3: Chiseled stone brick
        (void)meta;
        static const BlockTextures tex = {
            .top = tex_stonebrick,
            .bottom = tex_stonebrick,
            .north = tex_stonebrick,
            .south = tex_stonebrick,
            .east = tex_stonebrick,
            .west = tex_stonebrick,
        };
        return &tex;
    }

    case 99: { // Brown Mushroom (block)
        // Variants:
        //   meta 0: Pores on all sides
        //   meta 1: Cap texture on top, west and north
        //   meta 2: Cap texture on top and north
        //   meta 3: Cap texture on top, north and east
        //   meta 4: Cap texture on top and west
        //   meta 5: Cap texture on top
        //   meta 6: Cap texture on top and east
        //   meta 7: Cap texture on top, south and west
        //   meta 8: Cap texture on top and south
        //   meta 9: Cap texture on top, east and south
        //   meta 10: Stem texture on all four sides, pores on top and bottom
        //   meta 14: Cap texture on all six sides
        //   meta 15: Stem texture on all six sides
        (void)meta;
        static const BlockTextures tex = {
            .top = NULL,
            .bottom = NULL,
            .north = tex_mushroom_block_skin_brown,
            .south = tex_mushroom_block_inside,
            .east = tex_mushroom_block_inside,
            .west = tex_mushroom_block_skin_brown,
        };
        return &tex;
    }

    case 100: { // Red Mushroom (block)
        // Variants:
        //   meta 0: Pores on all sides
        //   meta 1: Cap texture on top, west and north
        //   meta 2: Cap texture on top and north
        //   meta 3: Cap texture on top, north and east
        //   meta 4: Cap texture on top and west
        //   meta 5: Cap texture on top
        //   meta 6: Cap texture on top and east
        //   meta 7: Cap texture on top, south and west
        //   meta 8: Cap texture on top and south
        //   meta 9: Cap texture on top, east and south
        //   meta 10: Stem texture on all four sides, pores on top and bottom
        //   meta 14: Cap texture on all six sides
        //   meta 15: Stem texture on all six sides
        (void)meta;
        static const BlockTextures tex = {
            .top = NULL,
            .bottom = NULL,
            .north = tex_mushroom_block_skin_red,
            .south = tex_mushroom_block_inside,
            .east = tex_mushroom_block_inside,
            .west = tex_mushroom_block_skin_red,
        };
        return &tex;
    }

    case 101: { // Iron Bars
        (void)meta;
        return NULL; // No model found
    }

    case 102: { // Glass Pane
        (void)meta;
        return NULL; // No model found
    }

    case 103: { // Melon
        (void)meta;
        static const BlockTextures tex = {
            .top = tex_melon_top,
            .bottom = tex_melon_top,
            .north = tex_melon_side,
            .south = tex_melon_side,
            .east = tex_melon_side,
            .west = tex_melon_side,
        };
        return &tex;
    }

    case 104: { // Pumpkin Stem
        (void)meta;
        return NULL; // No model found
    }

    case 105: { // Melon Stem
        (void)meta;
        return NULL; // No model found
    }

    case 106: { // Vines
        (void)meta;
        return NULL; // No model found
    }

    case 107: { // Fence Gate
        (void)meta;
        return NULL; // No model found
    }

    case 108: { // Brick Stairs
        (void)meta;
        static const BlockTextures tex = {
            .top = tex_brick,
            .bottom = tex_brick,
            .north = tex_brick,
            .south = tex_brick,
            .east = tex_brick,
            .west = tex_brick,
        };
        return &tex;
    }

    case 109: { // Stone Brick Stairs
        (void)meta;
        static const BlockTextures tex = {
            .top = tex_stonebrick,
            .bottom = tex_stonebrick,
            .north = tex_stonebrick,
            .south = tex_stonebrick,
            .east = tex_stonebrick,
            .west = tex_stonebrick,
        };
        return &tex;
    }

    case 110: { // Mycelium
        (void)meta;
        static const BlockTextures tex = {
            .top = tex_mycelium_top,
            .bottom = tex_dirt,
            .north = tex_mycelium_side,
            .south = tex_mycelium_side,
            .east = tex_mycelium_side,
            .west = tex_mycelium_side,
        };
        return &tex;
    }

    case 111: { // Lily Pad
        (void)meta;
        return NULL; // No model found
    }

    case 112: { // Nether Brick
        (void)meta;
        static const BlockTextures tex = {
            .top = tex_nether_brick,
            .bottom = tex_nether_brick,
            .north = tex_nether_brick,
            .south = tex_nether_brick,
            .east = tex_nether_brick,
            .west = tex_nether_brick,
        };
        return &tex;
    }

    case 113: { // Nether Brick Fence
        (void)meta;
        return NULL; // No model found
    }

    case 114: { // Nether Brick Stairs
        (void)meta;
        static const BlockTextures tex = {
            .top = tex_nether_brick,
            .bottom = tex_nether_brick,
            .north = tex_nether_brick,
            .south = tex_nether_brick,
            .east = tex_nether_brick,
            .west = tex_nether_brick,
        };
        return &tex;
    }

    case 115: { // Nether Wart
        (void)meta;
        return NULL; // No model found
    }

    case 116: { // Enchantment Table
        (void)meta;
        static const BlockTextures tex = {
            .top = tex_enchanting_table_top,
            .bottom = tex_enchanting_table_bottom,
            .north = tex_enchanting_table_side,
            .south = tex_enchanting_table_side,
            .east = tex_enchanting_table_side,
            .west = tex_enchanting_table_side,
        };
        return &tex;
    }

    case 117: { // Brewing Stand
        (void)meta;
        return NULL; // No model found
    }

    case 118: { // Cauldron
        (void)meta;
        static const BlockTextures tex = {
            .top = tex_cauldron_top,
            .bottom = tex_cauldron_bottom,
            .north = tex_cauldron_side,
            .south = tex_cauldron_side,
            .east = tex_cauldron_side,
            .west = tex_cauldron_side,
        };
        return &tex;
    }

    case 119: { // End Portal
        (void)meta;
        return NULL; // No model found
    }

    case 120: { // End Portal Block
        (void)meta;
        static const BlockTextures tex = {
            .top = tex_endframe_top,
            .bottom = tex_end_stone,
            .north = tex_endframe_side,
            .south = tex_endframe_side,
            .east = tex_endframe_side,
            .west = tex_endframe_side,
        };
        return &tex;
    }

    case 121: { // End Stone
        (void)meta;
        static const BlockTextures tex = {
            .top = tex_end_stone,
            .bottom = tex_end_stone,
            .north = tex_end_stone,
            .south = tex_end_stone,
            .east = tex_end_stone,
            .west = tex_end_stone,
        };
        return &tex;
    }

    case 122: { // Dragon Egg
        (void)meta;
        static const BlockTextures tex = {
            .top = tex_dragon_egg,
            .bottom = tex_dragon_egg,
            .north = tex_dragon_egg,
            .south = tex_dragon_egg,
            .east = tex_dragon_egg,
            .west = tex_dragon_egg,
        };
        return &tex;
    }

    case 123: { // Redstone Lamp (inactive)
        (void)meta;
        static const BlockTextures tex = {
            .top = tex_redstone_lamp_off,
            .bottom = tex_redstone_lamp_off,
            .north = tex_redstone_lamp_off,
            .south = tex_redstone_lamp_off,
            .east = tex_redstone_lamp_off,
            .west = tex_redstone_lamp_off,
        };
        return &tex;
    }

    case 124: { // Redstone Lamp (active)
        (void)meta;
        static const BlockTextures tex = {
            .top = tex_redstone_lamp_on,
            .bottom = tex_redstone_lamp_on,
            .north = tex_redstone_lamp_on,
            .south = tex_redstone_lamp_on,
            .east = tex_redstone_lamp_on,
            .west = tex_redstone_lamp_on,
        };
        return &tex;
    }

    case 125: { // Double Wooden Slab
        // Variants:
        //   meta 0: Double Oak Wood Slab
        //   meta 1: Double Spruce Wood Slab
        //   meta 2: Double Birch Wood Slab
        //   meta 3: Double Jungle Wood Slab
        //   meta 4: Double Acacia Wood Slab
        //   meta 5: Double Dark Oak Wood Slab
        (void)meta;
        static const BlockTextures tex = {
            .top = tex_planks_oak,
            .bottom = tex_planks_oak,
            .north = tex_planks_oak,
            .south = tex_planks_oak,
            .east = tex_planks_oak,
            .west = tex_planks_oak,
        };
        return &tex;
    }

    case 126: { // Wooden Slab
        // Variants:
        //   meta 0: Oak Wood Slab
        //   meta 1: Spruce Wood Slab
        //   meta 2: Birch Wood Slab
        //   meta 3: Jungle Wood Slab
        //   meta 4: Acacia Wood Slab
        //   meta 5: Dark Oak Wood Slab
        //   meta 8: Upper Oak Wood Slab
        //   meta 9: Upper Spruce Wood Slab
        //   meta 10: Upper Birch Wood Slab
        //   meta 11: Upper Jungle Wood Slab
        //   meta 12: Upper Acacia Wood Slab
        //   meta 13: Upper Dark Oak Wood Slab
        (void)meta;
        static const BlockTextures tex = {
            .top = tex_planks_oak,
            .bottom = tex_planks_oak,
            .north = tex_planks_oak,
            .south = tex_planks_oak,
            .east = tex_planks_oak,
            .west = tex_planks_oak,
        };
        return &tex;
    }

    case 127: { // Cocoa
        (void)meta;
        return NULL; // No model found
    }

    case 128: { // Sandstone Stairs
        (void)meta;
        static const BlockTextures tex = {
            .top = tex_sandstone_top,
            .bottom = tex_sandstone_bottom,
            .north = tex_sandstone_normal,
            .south = tex_sandstone_normal,
            .east = tex_sandstone_normal,
            .west = tex_sandstone_normal,
        };
        return &tex;
    }

    case 129: { // Emerald Ore
        (void)meta;
        static const BlockTextures tex = {
            .top = tex_emerald_ore,
            .bottom = tex_emerald_ore,
            .north = tex_emerald_ore,
            .south = tex_emerald_ore,
            .east = tex_emerald_ore,
            .west = tex_emerald_ore,
        };
        return &tex;
    }

    case 130: { // Ender Chest
        (void)meta;
        return NULL; // No model found
    }

    case 131: { // Tripwire Hook
        (void)meta;
        return NULL; // No model found
    }

    case 132: { // Tripwire
        (void)meta;
        return NULL; // No model found
    }

    case 133: { // Block of Emerald
        (void)meta;
        static const BlockTextures tex = {
            .top = tex_emerald_block,
            .bottom = tex_emerald_block,
            .north = tex_emerald_block,
            .south = tex_emerald_block,
            .east = tex_emerald_block,
            .west = tex_emerald_block,
        };
        return &tex;
    }

    case 134: { // Spruce Wood Stairs
        (void)meta;
        static const BlockTextures tex = {
            .top = tex_planks_spruce,
            .bottom = tex_planks_spruce,
            .north = tex_planks_spruce,
            .south = tex_planks_spruce,
            .east = tex_planks_spruce,
            .west = tex_planks_spruce,
        };
        return &tex;
    }

    case 135: { // Birch Wood Stairs
        (void)meta;
        static const BlockTextures tex = {
            .top = tex_planks_birch,
            .bottom = tex_planks_birch,
            .north = tex_planks_birch,
            .south = tex_planks_birch,
            .east = tex_planks_birch,
            .west = tex_planks_birch,
        };
        return &tex;
    }

    case 136: { // Jungle Wood Stairs
        (void)meta;
        static const BlockTextures tex = {
            .top = tex_planks_jungle,
            .bottom = tex_planks_jungle,
            .north = tex_planks_jungle,
            .south = tex_planks_jungle,
            .east = tex_planks_jungle,
            .west = tex_planks_jungle,
        };
        return &tex;
    }

    case 137: { // Command Block
        (void)meta;
        static const BlockTextures tex = {
            .top = tex_command_block,
            .bottom = tex_command_block,
            .north = tex_command_block,
            .south = tex_command_block,
            .east = tex_command_block,
            .west = tex_command_block,
        };
        return &tex;
    }

    case 138: { // Beacon
        (void)meta;
        return NULL; // No model found
    }

    case 139: { // Cobblestone Wall
        // Variants:
        //   meta 0: Cobblestone Wall
        //   meta 1: Mossy Cobblestone Wall
        (void)meta;
        return NULL; // No model found
    }

    case 140: { // Flower Pot
        // Variants:
        //   meta 0: Empty Flower Pot
        //   meta 1: Poppy Flower Pot
        //   meta 2: Dandelion Flower Pot
        //   meta 3: Oak sapling Flower Pot
        //   meta 4: Spruce sapling Flower Pot
        //   meta 5: Birch sapling Flower Pot
        //   meta 6: Jungle sapling Flower Pot
        //   meta 7: Red mushroom Flower Pot
        //   meta 8: Brown mushroom Flower Pot
        //   meta 9: Cactus Flower Pot
        //   meta 10: Dead bush Flower Pot
        //   meta 11: Fern Flower Pot
        //   meta 12: Acacia sapling Flower Pot
        //   meta 13: Dark oak sapling Flower Pot
        (void)meta;
        return NULL; // No model found
    }

    case 141: { // Carrot
        (void)meta;
        return NULL; // No model found
    }

    case 142: { // Potato
        (void)meta;
        return NULL; // No model found
    }

    case 143: { // Wooden Button
        (void)meta;
        return NULL; // No model found
    }

    case 144: { // Mob head
        // Variants:
        //   meta 0: Skeleton Skull
        //   meta 1: Wither Skeleton Skull
        //   meta 2: Zombie Head
        //   meta 3: Head
        //   meta 4: Creeper Head
        (void)meta;
        return NULL; // No model found
    }

    case 145: { // Anvil
        // Variants:
        //   meta 0: Anvil
        //   meta 1: Slightly Damaged Anvil
        //   meta 2: Very Damaged Anvil
        //   meta 3: Anvil (North/South)
        //   meta 4: Anvil (East/West)
        //   meta 5: Anvil (South/North)
        //   meta 6: Anvil (West/East)
        //   meta 7: Slightly Damaged Anvil (North/South)
        //   meta 8: Slightly Damaged Anvil (East/West)
        //   meta 9: Slightly Damaged Anvil (West/East)
        //   meta 10: Slightly Damaged Anvil (South/North)
        //   meta 11: Very Damaged Anvil (North/South)
        //   meta 12: Very Damaged Anvil (East/West)
        //   meta 13: Very Damaged Anvil (West/East)
        //   meta 14: Very Damaged Anvil (South/North)
        (void)meta;
        static const BlockTextures tex = {
            .top = tex_anvil_top_damaged_0,
            .bottom = NULL,
            .north = NULL,
            .south = NULL,
            .east = NULL,
            .west = NULL,
        };
        return &tex;
    }

    case 146: { // Trapped Chest
        (void)meta;
        return NULL; // No model found
    }

    case 147: { // Weighted Pressure Plate (Light)
        (void)meta;
        return NULL; // No model found
    }

    case 148: { // Weighted Pressure Plate (Heavy)
        (void)meta;
        return NULL; // No model found
    }

    case 149: { // Redstone Comparator
        (void)meta;
        static const BlockTextures tex = {
            .top = tex_comparator_off,
            .bottom = NULL,
            .north = NULL,
            .south = NULL,
            .east = NULL,
            .west = NULL,
        };
        return &tex;
    }

    case 150: { // Redstone Comparator (deprecated)
        (void)meta;
        static const BlockTextures tex = {
            .top = tex_comparator_off,
            .bottom = NULL,
            .north = NULL,
            .south = NULL,
            .east = NULL,
            .west = NULL,
        };
        return &tex;
    }

    case 151: { // Daylight Sensor
        (void)meta;
        static const BlockTextures tex = {
            .top = tex_daylight_detector_top,
            .bottom = NULL,
            .north = tex_daylight_detector_side,
            .south = tex_daylight_detector_side,
            .east = tex_daylight_detector_side,
            .west = tex_daylight_detector_side,
        };
        return &tex;
    }

    case 152: { // Block of Redstone
        (void)meta;
        static const BlockTextures tex = {
            .top = tex_redstone_block,
            .bottom = tex_redstone_block,
            .north = tex_redstone_block,
            .south = tex_redstone_block,
            .east = tex_redstone_block,
            .west = tex_redstone_block,
        };
        return &tex;
    }

    case 153: { // Nether Quartz Ore
        (void)meta;
        static const BlockTextures tex = {
            .top = tex_quartz_ore,
            .bottom = tex_quartz_ore,
            .north = tex_quartz_ore,
            .south = tex_quartz_ore,
            .east = tex_quartz_ore,
            .west = tex_quartz_ore,
        };
        return &tex;
    }

    case 154: { // Hopper
        (void)meta;
        static const BlockTextures tex = {
            .top = tex_hopper_top,
            .bottom = NULL,
            .north = tex_hopper_outside,
            .south = tex_hopper_outside,
            .east = tex_hopper_outside,
            .west = tex_hopper_outside,
        };
        return &tex;
    }

    case 155: { // Block of Quartz
        // Variants:
        //   meta 0: Block of Quartz
        //   meta 1: Chiseled Quartz Block
        //   meta 2: Pillar Quartz Block (vertical)
        //   meta 3: Pillar Quartz Block (north-south)
        //   meta 4: Pillar Quartz Block (east-west)
        (void)meta;
        static const BlockTextures tex = {
            .top = tex_quartz_block_top,
            .bottom = tex_quartz_block_bottom,
            .north = tex_quartz_block_side,
            .south = tex_quartz_block_side,
            .east = tex_quartz_block_side,
            .west = tex_quartz_block_side,
        };
        return &tex;
    }

    case 156: { // Quartz Stairs
        (void)meta;
        static const BlockTextures tex = {
            .top = tex_quartz_block_top,
            .bottom = tex_quartz_block_bottom,
            .north = tex_quartz_block_side,
            .south = tex_quartz_block_side,
            .east = tex_quartz_block_side,
            .west = tex_quartz_block_side,
        };
        return &tex;
    }

    case 157: { // Activator Rail
        (void)meta;
        return NULL; // No model found
    }

    case 158: { // Dropper
        (void)meta;
        static const BlockTextures tex = {
            .top = NULL,
            .bottom = NULL,
            .north = tex_dropper_front_vertical,
            .south = tex_furnace_top,
            .east = tex_furnace_top,
            .west = tex_furnace_top,
        };
        return &tex;
    }

    case 159: { // Stained Clay
        (void)meta;
        static const BlockTextures tex = {
            .top = tex_hardened_clay_stained_white,
            .bottom = tex_hardened_clay_stained_white,
            .north = tex_hardened_clay_stained_white,
            .south = tex_hardened_clay_stained_white,
            .east = tex_hardened_clay_stained_white,
            .west = tex_hardened_clay_stained_white,
        };
        return &tex;
    }

    case 160: { // Stained Glass Pane
        (void)meta;
        return NULL; // No model found
    }

    case 161: { // Leaves (Acacia/Dark Oak)
        // Variants:
        //   meta 0: Acacia Leaves
        //   meta 1: Dark Oak Leaves
        //   meta 4: Acacia Leaves (no decay)
        //   meta 5: Dark Oak Leaves (no decay)
        //   meta 8: Acacia Leaves (check decay)
        //   meta 9: Dark Oak Leaves (check decay)
        //   meta 12: Acacia Leaves (no decay and check decay)
        //   meta 13: Dark Oak Leaves (no decay and check decay)
        (void)meta;
        static const BlockTextures tex = {
            .top = tex_leaves_acacia,
            .bottom = tex_leaves_acacia,
            .north = tex_leaves_acacia,
            .south = tex_leaves_acacia,
            .east = tex_leaves_acacia,
            .west = tex_leaves_acacia,
        };
        return &tex;
    }

    case 162: { // Wood (Acacia/Dark Oak)
        // Variants:
        //   meta 0: Acacia wood facing up/down
        //   meta 1: Dark Oak wood facing up/down
        //   meta 4: Acacia wood facing East/West
        //   meta 5: Dark Oak wood facing East/West
        //   meta 8: Acacia wood facing North/South
        //   meta 9: Dark Oak wood facing North/South
        //   meta 12: Acacia wood with only bark
        //   meta 13: Dark Oak wood with only bark
        (void)meta;
        static const BlockTextures tex = {
            .top = tex_log_acacia_top,
            .bottom = tex_log_acacia_top,
            .north = tex_log_acacia,
            .south = tex_log_acacia,
            .east = tex_log_acacia,
            .west = tex_log_acacia,
        };
        return &tex;
    }

    case 163: { // Acacia Wood Stairs
        (void)meta;
        static const BlockTextures tex = {
            .top = tex_planks_acacia,
            .bottom = tex_planks_acacia,
            .north = tex_planks_acacia,
            .south = tex_planks_acacia,
            .east = tex_planks_acacia,
            .west = tex_planks_acacia,
        };
        return &tex;
    }

    case 164: { // Dark Oak Wood Stairs
        (void)meta;
        static const BlockTextures tex = {
            .top = tex_planks_big_oak,
            .bottom = tex_planks_big_oak,
            .north = tex_planks_big_oak,
            .south = tex_planks_big_oak,
            .east = tex_planks_big_oak,
            .west = tex_planks_big_oak,
        };
        return &tex;
    }

    case 165: { // Slime Block
        (void)meta;
        return NULL; // No model found
    }

    case 166: { // Barrier
        (void)meta;
        return NULL; // No model found
    }

    case 167: { // Iron Trapdoor
        (void)meta;
        return NULL; // No model found
    }

    case 168: { // Prismarine
        // Variants:
        //   meta 0: Prismarine
        //   meta 1: Prismarine Bricks
        //   meta 2: Dark Prismarine
        (void)meta;
        static const BlockTextures tex = {
            .top = tex_prismarine_rough,
            .bottom = tex_prismarine_rough,
            .north = tex_prismarine_rough,
            .south = tex_prismarine_rough,
            .east = tex_prismarine_rough,
            .west = tex_prismarine_rough,
        };
        return &tex;
    }

    case 169: { // Sea Lantern
        (void)meta;
        static const BlockTextures tex = {
            .top = tex_sea_lantern,
            .bottom = tex_sea_lantern,
            .north = tex_sea_lantern,
            .south = tex_sea_lantern,
            .east = tex_sea_lantern,
            .west = tex_sea_lantern,
        };
        return &tex;
    }

    case 170: { // Hay Bale
        (void)meta;
        static const BlockTextures tex = {
            .top = tex_hay_block_top,
            .bottom = tex_hay_block_top,
            .north = tex_hay_block_side,
            .south = tex_hay_block_side,
            .east = tex_hay_block_side,
            .west = tex_hay_block_side,
        };
        return &tex;
    }

    case 171: { // Carpet
        // Variants:
        //   meta 0: White Carpet
        //   meta 1: Orange Carpet
        //   meta 2: Magenta Carpet
        //   meta 3: Light Blue Carpet
        //   meta 4: Yellow Carpet
        //   meta 5: Lime Carpet
        //   meta 6: Pink Carpet
        //   meta 7: Gray Carpet
        //   meta 8: Light Gray Carpet
        //   meta 9: Cyan Carpet
        //   meta 10: Purple Carpet
        //   meta 11: Blue Carpet
        //   meta 12: Brown Carpet
        //   meta 13: Green Carpet
        //   meta 14: Red Carpet
        //   meta 15: Black Carpet
        (void)meta;
        return NULL; // No model found
    }

    case 172: { // Hardened Clay
        (void)meta;
        static const BlockTextures tex = {
            .top = tex_hardened_clay,
            .bottom = tex_hardened_clay,
            .north = tex_hardened_clay,
            .south = tex_hardened_clay,
            .east = tex_hardened_clay,
            .west = tex_hardened_clay,
        };
        return &tex;
    }

    case 173: { // Block of Coal
        (void)meta;
        static const BlockTextures tex = {
            .top = tex_coal_block,
            .bottom = tex_coal_block,
            .north = tex_coal_block,
            .south = tex_coal_block,
            .east = tex_coal_block,
            .west = tex_coal_block,
        };
        return &tex;
    }

    case 174: { // Packed Ice
        (void)meta;
        static const BlockTextures tex = {
            .top = tex_ice_packed,
            .bottom = tex_ice_packed,
            .north = tex_ice_packed,
            .south = tex_ice_packed,
            .east = tex_ice_packed,
            .west = tex_ice_packed,
        };
        return &tex;
    }

    case 175: { // Large Flowers
        // Variants:
        //   meta 0: Sunflower
        //   meta 1: Lilac
        //   meta 2: Double Tallgrass
        //   meta 3: Large Fern
        //   meta 4: Rose Bush
        //   meta 5: Peony
        //   meta 8: Top Half of any Large Plant; low three bits 0x7 are derived from the block below.
        (void)meta;
        static const BlockTextures tex = {
            .top = tex_double_plant_sunflower_bottom,
            .bottom = tex_double_plant_sunflower_bottom,
            .north = tex_double_plant_sunflower_bottom,
            .south = tex_double_plant_sunflower_bottom,
            .east = tex_double_plant_sunflower_bottom,
            .west = tex_double_plant_sunflower_bottom,
        };
        return &tex;
    }

    case 176: { // Standing Banner
        (void)meta;
        return NULL; // No model found
    }

    case 177: { // Wall Banner
        (void)meta;
        return NULL; // No model found
    }

    case 178: { // Inverted Daylight Sensor
        (void)meta;
        static const BlockTextures tex = {
            .top = tex_daylight_detector_inverted_top,
            .bottom = NULL,
            .north = tex_daylight_detector_side,
            .south = tex_daylight_detector_side,
            .east = tex_daylight_detector_side,
            .west = tex_daylight_detector_side,
        };
        return &tex;
    }

    case 179: { // Red Sandstone
        // Variants:
        //   meta 0: Sandstone
        //   meta 1: Chiseled sandstone
        //   meta 2: Smooth sandstone
        (void)meta;
        static const BlockTextures tex = {
            .top = tex_red_sandstone_top,
            .bottom = tex_red_sandstone_bottom,
            .north = tex_red_sandstone_normal,
            .south = tex_red_sandstone_normal,
            .east = tex_red_sandstone_normal,
            .west = tex_red_sandstone_normal,
        };
        return &tex;
    }

    case 180: { // Red Sandstone Stairs
        (void)meta;
        static const BlockTextures tex = {
            .top = tex_red_sandstone_top,
            .bottom = tex_red_sandstone_bottom,
            .north = tex_red_sandstone_normal,
            .south = tex_red_sandstone_normal,
            .east = tex_red_sandstone_normal,
            .west = tex_red_sandstone_normal,
        };
        return &tex;
    }

    case 181: { // Double Red Sandstone Slab
        // Variants:
        //   meta 0: Double Red Sandstone Slab
        //   meta 8: Smooth Double Red Sandstone Slab
        (void)meta;
        static const BlockTextures tex = {
            .top = tex_red_sandstone_top,
            .bottom = tex_red_sandstone_bottom,
            .north = tex_red_sandstone_normal,
            .south = tex_red_sandstone_normal,
            .east = tex_red_sandstone_normal,
            .west = tex_red_sandstone_normal,
        };
        return &tex;
    }

    case 182: { // Red Sandstone Slab
        // Variants:
        //   meta 0: Red Sandstone Slab
        //   meta 8: Upper Red Sandstone Slab
        (void)meta;
        static const BlockTextures tex = {
            .top = tex_red_sandstone_top,
            .bottom = tex_red_sandstone_bottom,
            .north = tex_red_sandstone_normal,
            .south = tex_red_sandstone_normal,
            .east = tex_red_sandstone_normal,
            .west = tex_red_sandstone_normal,
        };
        return &tex;
    }

    case 183: { // Spruce Fence Gate
        (void)meta;
        return NULL; // No model found
    }

    case 184: { // Birch Fence Gate
        (void)meta;
        return NULL; // No model found
    }

    case 185: { // Jungle Fence Gate
        (void)meta;
        return NULL; // No model found
    }

    case 186: { // Dark Oak Fence Gate
        (void)meta;
        return NULL; // No model found
    }

    case 187: { // Acacia Fence Gate
        (void)meta;
        return NULL; // No model found
    }

    case 188: { // Spruce Fence
        (void)meta;
        return NULL; // No model found
    }

    case 189: { // Birch Fence
        (void)meta;
        return NULL; // No model found
    }

    case 190: { // Jungle Fence
        (void)meta;
        return NULL; // No model found
    }

    case 191: { // Dark Oak Fence
        (void)meta;
        return NULL; // No model found
    }

    case 192: { // Acacia Fence
        (void)meta;
        return NULL; // No model found
    }

    case 193: { // Spruce Door
        (void)meta;
        static const BlockTextures tex = {
            .top = tex_door_spruce_upper,
            .bottom = tex_door_spruce_lower,
            .north = NULL,
            .south = NULL,
            .east = NULL,
            .west = NULL,
        };
        return &tex;
    }

    case 194: { // Birch Door
        (void)meta;
        static const BlockTextures tex = {
            .top = tex_door_birch_upper,
            .bottom = tex_door_birch_lower,
            .north = NULL,
            .south = NULL,
            .east = NULL,
            .west = NULL,
        };
        return &tex;
    }

    case 195: { // Jungle Door
        (void)meta;
        static const BlockTextures tex = {
            .top = tex_door_jungle_upper,
            .bottom = tex_door_jungle_lower,
            .north = NULL,
            .south = NULL,
            .east = NULL,
            .west = NULL,
        };
        return &tex;
    }

    case 196: { // Acacia Door
        (void)meta;
        static const BlockTextures tex = {
            .top = tex_door_acacia_upper,
            .bottom = tex_door_acacia_lower,
            .north = NULL,
            .south = NULL,
            .east = NULL,
            .west = NULL,
        };
        return &tex;
    }

    case 197: { // Dark Oak Door
        (void)meta;
        static const BlockTextures tex = {
            .top = tex_door_dark_oak_upper,
            .bottom = tex_door_dark_oak_lower,
            .north = NULL,
            .south = NULL,
            .east = NULL,
            .west = NULL,
        };
        return &tex;
    }

    default:
        return NULL;
    }
}