#include "block_properties.h"

// Auto-generated block properties from blocks.json and blocks_models.json

bool get_is_full_opaque(uint16_t block_id) {
    switch(block_id) {
    case 0: return false; // air
    case 6: return false; // sapling
    case 8: return false; // flowing_water
    case 9: return false; // water
    case 10: return false; // flowing_lava
    case 11: return false; // lava
    case 18: return false; // leaves
    case 20: return false; // glass
    case 26: return false; // bed
    case 27: return false; // golden_rail
    case 28: return false; // detector_rail
    case 29: return false; // sticky_piston
    case 30: return false; // web
    case 31: return false; // tallgrass
    case 32: return false; // deadbush
    case 33: return false; // piston
    case 43: return false; // double_stone_slab
    case 44: return false; // stone_slab
    case 46: return false; // tnt
    case 50: return false; // torch
    case 51: return false; // fire
    case 52: return false; // mob_spawner
    case 53: return false; // oak_stairs
    case 54: return false; // chest
    case 55: return false; // redstone_wire
    case 59: return false; // wheat
    case 60: return false; // farmland
    case 61: return false; // furnace
    case 62: return false; // lit_furnace
    case 63: return false; // standing_sign
    case 64: return false; // wooden_door
    case 65: return false; // ladder
    case 66: return false; // rail
    case 67: return false; // stone_stairs
    case 68: return false; // wall_sign
    case 69: return false; // lever
    case 70: return false; // stone_pressure_plate
    case 71: return false; // iron_door
    case 72: return false; // wooden_pressure_plate
    case 73: return false; // redstone_ore
    case 74: return false; // lit_redstone_ore
    case 75: return false; // unlit_redstone_torch
    case 76: return false; // redstone_torch
    case 77: return false; // stone_button
    case 78: return false; // snow_layer
    case 79: return false; // ice
    case 81: return false; // cactus
    case 83: return false; // reeds
    case 85: return false; // fence
    case 86: return false; // pumpkin
    case 89: return false; // glowstone
    case 91: return false; // lit_pumpkin
    case 92: return false; // cake
    case 93: return false; // unpowered_repeater
    case 94: return false; // powered_repeater
    case 95: return false; // stained_glass
    case 96: return false; // trapdoor
    case 101: return false; // iron_bars
    case 102: return false; // glass_pane
    case 103: return false; // melon_block
    case 104: return false; // pumpkin_stem
    case 105: return false; // melon_stem
    case 106: return false; // vine
    case 107: return false; // fence_gate
    case 108: return false; // brick_stairs
    case 109: return false; // stone_brick_stairs
    case 111: return false; // waterlily
    case 113: return false; // nether_brick_fence
    case 114: return false; // nether_brick_stairs
    case 115: return false; // nether_wart
    case 116: return false; // enchanting_table
    case 117: return false; // brewing_stand
    case 118: return false; // cauldron
    case 120: return false; // end_portal_frame
    case 122: return false; // dragon_egg
    case 123: return false; // redstone_lamp
    case 124: return false; // lit_redstone_lamp
    case 125: return false; // double_wooden_slab
    case 126: return false; // wooden_slab
    case 127: return false; // cocoa
    case 128: return false; // sandstone_stairs
    case 130: return false; // ender_chest
    case 131: return false; // tripwire_hook
    case 132: return false; // tripwire
    case 134: return false; // spruce_stairs
    case 135: return false; // birch_stairs
    case 136: return false; // jungle_stairs
    case 138: return false; // beacon
    case 139: return false; // cobblestone_wall
    case 140: return false; // flower_pot
    case 143: return false; // wooden_button
    case 144: return false; // skull
    case 145: return false; // anvil
    case 146: return false; // trapped_chest
    case 147: return false; // light_weighted_pressure_plate
    case 148: return false; // heavy_weighted_pressure_plate
    case 149: return false; // unpowered_comparator
    case 150: return false; // powered_comparator
    case 151: return false; // daylight_detector
    case 152: return false; // redstone_block
    case 154: return false; // hopper
    case 156: return false; // quartz_stairs
    case 157: return false; // activator_rail
    case 160: return false; // stained_glass_pane
    case 161: return false; // leaves2
    case 163: return false; // acacia_stairs
    case 164: return false; // dark_oak_stairs
    case 165: return false; // slime
    case 166: return false; // barrier
    case 167: return false; // iron_trapdoor
    case 169: return false; // sea_lantern
    case 171: return false; // carpet
    case 176: return false; // standing_banner
    case 177: return false; // wall_banner
    case 178: return false; // daylight_detector_inverted
    case 180: return false; // red_sandstone_stairs
    case 181: return false; // double_stone_slab2
    case 182: return false; // stone_slab2
    case 183: return false; // spruce_fence_gate
    case 184: return false; // birch_fence_gate
    case 185: return false; // jungle_fence_gate
    case 186: return false; // dark_oak_fence_gate
    case 187: return false; // acacia_fence_gate
    case 188: return false; // spruce_fence
    case 189: return false; // birch_fence
    case 190: return false; // jungle_fence
    case 191: return false; // dark_oak_fence
    case 192: return false; // acacia_fence
    case 193: return false; // spruce_door
    case 194: return false; // birch_door
    case 195: return false; // jungle_door
    case 196: return false; // acacia_door
    case 197: return false; // dark_oak_door
    default: return true;
    }
}

BlockModelType get_block_model_type(uint16_t block_id) {
    switch(block_id) {
    case 1: return MODEL_CUBE; // stone
    case 2: return MODEL_GRASS; // grass
    case 3: return MODEL_CUBE; // dirt
    case 4: return MODEL_CUBE; // cobblestone
    case 5: return MODEL_CUBE; // planks
    case 6: return MODEL_CROSS; // sapling
    case 7: return MODEL_CUBE; // bedrock
    case 12: return MODEL_CUBE; // sand
    case 13: return MODEL_CUBE; // gravel
    case 14: return MODEL_CUBE; // gold_ore
    case 15: return MODEL_CUBE; // iron_ore
    case 16: return MODEL_CUBE; // coal_ore
    case 17: return MODEL_CUBE; // log
    case 18: return MODEL_LEAVES; // leaves
    case 19: return MODEL_CUBE; // sponge
    case 20: return MODEL_CUBE; // glass
    case 21: return MODEL_CUBE; // lapis_ore
    case 22: return MODEL_CUBE; // lapis_block
    case 23: return MODEL_CUBE; // dispenser
    case 24: return MODEL_CUBE; // sandstone
    case 25: return MODEL_CUBE; // noteblock
    case 26: return MODEL_BED_FOOT; // bed
    case 27: return MODEL_RAIL_FLAT; // golden_rail
    case 28: return MODEL_RAIL_FLAT; // detector_rail
    case 29: return MODEL_PISTON; // sticky_piston
    case 30: return MODEL_CROSS; // web
    case 31: return MODEL_TALLGRASS; // tallgrass
    case 32: return MODEL_CROSS; // deadbush
    case 33: return MODEL_PISTON; // piston
    case 34: return MODEL_PISTON_HEAD; // piston_head
    case 35: return MODEL_CUBE; // wool
    case 36: return MODEL_PISTON; // piston_extension
    case 37: return MODEL_CROSS; // yellow_flower
    case 38: return MODEL_CROSS; // red_flower
    case 39: return MODEL_CROSS; // brown_mushroom
    case 40: return MODEL_CROSS; // red_mushroom
    case 41: return MODEL_CUBE; // gold_block
    case 42: return MODEL_CUBE; // iron_block
    case 43: return MODEL_CUBE; // double_stone_slab
    case 44: return MODEL_HALF_SLAB; // stone_slab
    case 45: return MODEL_CUBE; // brick_block
    case 46: return MODEL_CUBE; // tnt
    case 47: return MODEL_CUBE; // bookshelf
    case 48: return MODEL_CUBE; // mossy_cobblestone
    case 49: return MODEL_CUBE; // obsidian
    case 50: return MODEL_TORCH; // torch
    case 51: return MODEL_FIRE_FLOOR; // fire
    case 52: return MODEL_CUBE; // mob_spawner
    case 53: return MODEL_STAIRS; // oak_stairs
    case 55: return MODEL_REDSTONE_NONE; // redstone_wire
    case 56: return MODEL_CUBE; // diamond_ore
    case 57: return MODEL_CUBE; // diamond_block
    case 58: return MODEL_CUBE; // crafting_table
    case 59: return MODEL_CROP; // wheat
    case 60: return MODEL_FARMLAND; // farmland
    case 61: return MODEL_CUBE; // furnace
    case 62: return MODEL_CUBE; // lit_furnace
    case 64: return MODEL_DOOR_BOTTOM; // wooden_door
    case 65: return MODEL_LADDER; // ladder
    case 66: return MODEL_RAIL_FLAT; // rail
    case 67: return MODEL_STAIRS; // stone_stairs
    case 69: return MODEL_LEVER_OFF; // lever
    case 70: return MODEL_PRESSURE_PLATE_UP; // stone_pressure_plate
    case 71: return MODEL_DOOR_BOTTOM; // iron_door
    case 72: return MODEL_PRESSURE_PLATE_UP; // wooden_pressure_plate
    case 73: return MODEL_CUBE; // redstone_ore
    case 74: return MODEL_CUBE; // lit_redstone_ore
    case 75: return MODEL_TORCH; // unlit_redstone_torch
    case 76: return MODEL_TORCH; // redstone_torch
    case 77: return MODEL_BUTTON; // stone_button
    case 78: return MODEL_SNOW_HEIGHT2; // snow_layer
    case 79: return MODEL_CUBE; // ice
    case 80: return MODEL_CUBE; // snow
    case 81: return MODEL_CACTUS; // cactus
    case 82: return MODEL_CUBE; // clay
    case 83: return MODEL_TALLGRASS; // reeds
    case 84: return MODEL_CUBE; // jukebox
    case 85: return MODEL_FENCE_POST; // fence
    case 86: return MODEL_CUBE; // pumpkin
    case 87: return MODEL_CUBE; // netherrack
    case 88: return MODEL_CUBE; // soul_sand
    case 89: return MODEL_CUBE; // glowstone
    case 90: return MODEL_PORTAL_EW; // portal
    case 91: return MODEL_CUBE; // lit_pumpkin
    case 92: return MODEL_CAKE_UNEATEN; // cake
    case 93: return MODEL_REPEATER_1TICK; // unpowered_repeater
    case 94: return MODEL_REPEATER_ON_1TICK; // powered_repeater
    case 95: return MODEL_CUBE; // stained_glass
    case 96: return MODEL_TRAPDOOR_BOTTOM; // trapdoor
    case 98: return MODEL_CUBE; // stonebrick
    case 99: return MODEL_CUBE; // brown_mushroom_block
    case 100: return MODEL_CUBE; // red_mushroom_block
    case 101: return MODEL_BARS_NSEW; // iron_bars
    case 102: return MODEL_PANE_NSEW; // glass_pane
    case 103: return MODEL_CUBE; // melon_block
    case 104: return MODEL_STEM_GROWTH0; // pumpkin_stem
    case 105: return MODEL_STEM_GROWTH0; // melon_stem
    case 106: return MODEL_VINE_1; // vine
    case 107: return MODEL_FENCE_GATE_CLOSED; // fence_gate
    case 108: return MODEL_STAIRS; // brick_stairs
    case 109: return MODEL_STAIRS; // stone_brick_stairs
    case 110: return MODEL_CUBE; // mycelium
    case 111: return MODEL_WATERLILY; // waterlily
    case 112: return MODEL_CUBE; // nether_brick
    case 113: return MODEL_FENCE_POST; // nether_brick_fence
    case 114: return MODEL_STAIRS; // nether_brick_stairs
    case 115: return MODEL_CROP; // nether_wart
    case 116: return MODEL_ENCHANTING_TABLE_BASE; // enchanting_table
    case 117: return MODEL_BREWING_STAND_EMPTY; // brewing_stand
    case 118: return MODEL_CAULDRON_EMPTY; // cauldron
    case 120: return MODEL_END_PORTAL_FRAME_EMPTY; // end_portal_frame
    case 121: return MODEL_CUBE; // end_stone
    case 122: return MODEL_DRAGON_EGG; // dragon_egg
    case 123: return MODEL_CUBE; // redstone_lamp
    case 124: return MODEL_CUBE; // lit_redstone_lamp
    case 125: return MODEL_CUBE; // double_wooden_slab
    case 126: return MODEL_HALF_SLAB; // wooden_slab
    case 127: return MODEL_COCOA_AGE0_S; // cocoa
    case 128: return MODEL_STAIRS; // sandstone_stairs
    case 129: return MODEL_CUBE; // emerald_ore
    case 131: return MODEL_TRIPWIRE_HOOK; // tripwire_hook
    case 132: return MODEL_TRIPWIRE_NS; // tripwire
    case 133: return MODEL_CUBE; // emerald_block
    case 134: return MODEL_STAIRS; // spruce_stairs
    case 135: return MODEL_STAIRS; // birch_stairs
    case 136: return MODEL_STAIRS; // jungle_stairs
    case 137: return MODEL_CUBE; // command_block
    case 138: return MODEL_BEACON; // beacon
    case 139: return MODEL_WALL_POST; // cobblestone_wall
    case 140: return MODEL_FLOWER_POT; // flower_pot
    case 141: return MODEL_CROP; // carrots
    case 142: return MODEL_CROP; // potatoes
    case 143: return MODEL_BUTTON; // wooden_button
    case 145: return MODEL_ANVIL; // anvil
    case 147: return MODEL_PRESSURE_PLATE_UP; // light_weighted_pressure_plate
    case 148: return MODEL_PRESSURE_PLATE_UP; // heavy_weighted_pressure_plate
    case 149: return MODEL_COMPARATOR_UNLIT; // unpowered_comparator
    case 150: return MODEL_COMPARATOR_UNLIT; // powered_comparator
    case 151: return MODEL_DAYLIGHT_DETECTOR; // daylight_detector
    case 152: return MODEL_CUBE; // redstone_block
    case 153: return MODEL_CUBE; // quartz_ore
    case 154: return MODEL_HOPPER_DOWN; // hopper
    case 155: return MODEL_CUBE; // quartz_block
    case 156: return MODEL_STAIRS; // quartz_stairs
    case 157: return MODEL_RAIL_FLAT; // activator_rail
    case 158: return MODEL_CUBE; // dropper
    case 159: return MODEL_CUBE; // stained_hardened_clay
    case 160: return MODEL_PANE_NSEW; // stained_glass_pane
    case 161: return MODEL_LEAVES; // leaves2
    case 162: return MODEL_CUBE; // log2
    case 163: return MODEL_STAIRS; // acacia_stairs
    case 164: return MODEL_STAIRS; // dark_oak_stairs
    case 165: return MODEL_SLIME; // slime
    case 167: return MODEL_TRAPDOOR_BOTTOM; // iron_trapdoor
    case 168: return MODEL_CUBE; // prismarine
    case 169: return MODEL_CUBE; // sea_lantern
    case 170: return MODEL_CUBE; // hay_block
    case 171: return MODEL_CARPET; // carpet
    case 172: return MODEL_CUBE; // hardened_clay
    case 173: return MODEL_CUBE; // coal_block
    case 174: return MODEL_CUBE; // packed_ice
    case 175: return MODEL_CROSS; // double_plant
    case 178: return MODEL_DAYLIGHT_DETECTOR_INVERTED; // daylight_detector_inverted
    case 179: return MODEL_CUBE; // red_sandstone
    case 180: return MODEL_STAIRS; // red_sandstone_stairs
    case 181: return MODEL_CUBE; // double_stone_slab2
    case 182: return MODEL_HALF_SLAB; // stone_slab2
    case 183: return MODEL_FENCE_GATE_CLOSED; // spruce_fence_gate
    case 184: return MODEL_FENCE_GATE_CLOSED; // birch_fence_gate
    case 185: return MODEL_FENCE_GATE_CLOSED; // jungle_fence_gate
    case 186: return MODEL_FENCE_GATE_CLOSED; // dark_oak_fence_gate
    case 187: return MODEL_FENCE_GATE_CLOSED; // acacia_fence_gate
    case 188: return MODEL_FENCE_POST; // spruce_fence
    case 189: return MODEL_FENCE_POST; // birch_fence
    case 190: return MODEL_FENCE_POST; // jungle_fence
    case 191: return MODEL_FENCE_POST; // dark_oak_fence
    case 192: return MODEL_FENCE_POST; // acacia_fence
    case 193: return MODEL_DOOR_BOTTOM; // spruce_door
    case 194: return MODEL_DOOR_BOTTOM; // birch_door
    case 195: return MODEL_DOOR_BOTTOM; // jungle_door
    case 196: return MODEL_DOOR_BOTTOM; // acacia_door
    case 197: return MODEL_DOOR_BOTTOM; // dark_oak_door
    default: return MODEL_UNKNOWN;
    }
}

bool get_block_minable(uint16_t block_id) {
    switch(block_id) {
    case 0: return false; // air
    case 7: return false; // bedrock
    case 8: return false; // flowing_water
    case 9: return false; // water
    case 10: return false; // flowing_lava
    case 11: return false; // lava
    case 36: return false; // piston_extension
    case 90: return false; // portal
    case 119: return false; // end_portal
    case 120: return false; // end_portal_frame
    case 137: return false; // command_block
    case 166: return false; // barrier
    default: return true;
    }
}

float get_block_hardness(uint16_t block_id) {
    switch(block_id) {
    case 0: return 0.0f; // air
    case 1: return 1.5f; // stone
    case 2: return 0.6f; // grass
    case 3: return 0.5f; // dirt
    case 4: return 2.0f; // cobblestone
    case 5: return 2.0f; // planks
    case 6: return 0.0f; // sapling
    case 7: return -1.0f; // bedrock
    case 8: return 100.0f; // flowing_water
    case 9: return 100.0f; // water
    case 10: return 100.0f; // flowing_lava
    case 11: return 100.0f; // lava
    case 12: return 0.5f; // sand
    case 13: return 0.6f; // gravel
    case 14: return 3.0f; // gold_ore
    case 15: return 3.0f; // iron_ore
    case 16: return 3.0f; // coal_ore
    case 17: return 2.0f; // log
    case 18: return 0.2f; // leaves
    case 19: return 0.6f; // sponge
    case 20: return 0.3f; // glass
    case 21: return 3.0f; // lapis_ore
    case 22: return 3.0f; // lapis_block
    case 23: return 3.5f; // dispenser
    case 24: return 0.8f; // sandstone
    case 25: return 0.8f; // noteblock
    case 26: return 0.2f; // bed
    case 27: return 0.7f; // golden_rail
    case 28: return 0.7f; // detector_rail
    case 29: return 0.5f; // sticky_piston
    case 30: return 4.0f; // web
    case 31: return 0.0f; // tallgrass
    case 32: return 0.0f; // deadbush
    case 33: return 0.5f; // piston
    case 34: return 0.5f; // piston_head
    case 35: return 0.8f; // wool
    case 36: return -1.0f; // piston_extension
    case 37: return 0.0f; // yellow_flower
    case 38: return 0.0f; // red_flower
    case 39: return 0.0f; // brown_mushroom
    case 40: return 0.0f; // red_mushroom
    case 41: return 3.0f; // gold_block
    case 42: return 5.0f; // iron_block
    case 43: return 2.0f; // double_stone_slab
    case 44: return 2.0f; // stone_slab
    case 45: return 2.0f; // brick_block
    case 46: return 0.0f; // tnt
    case 47: return 1.5f; // bookshelf
    case 48: return 2.0f; // mossy_cobblestone
    case 49: return 50.0f; // obsidian
    case 50: return 0.0f; // torch
    case 51: return 0.0f; // fire
    case 52: return 5.0f; // mob_spawner
    case 53: return 2.0f; // oak_stairs
    case 54: return 2.5f; // chest
    case 55: return 0.0f; // redstone_wire
    case 56: return 3.0f; // diamond_ore
    case 57: return 5.0f; // diamond_block
    case 58: return 2.5f; // crafting_table
    case 59: return 0.0f; // wheat
    case 60: return 0.6f; // farmland
    case 61: return 3.5f; // furnace
    case 62: return 3.5f; // lit_furnace
    case 63: return 1.0f; // standing_sign
    case 64: return 3.0f; // wooden_door
    case 65: return 0.4f; // ladder
    case 66: return 0.7f; // rail
    case 67: return 2.0f; // stone_stairs
    case 68: return 1.0f; // wall_sign
    case 69: return 0.5f; // lever
    case 70: return 0.5f; // stone_pressure_plate
    case 71: return 5.0f; // iron_door
    case 72: return 0.5f; // wooden_pressure_plate
    case 73: return 3.0f; // redstone_ore
    case 74: return 3.0f; // lit_redstone_ore
    case 75: return 0.0f; // unlit_redstone_torch
    case 76: return 0.0f; // redstone_torch
    case 77: return 0.5f; // stone_button
    case 78: return 0.2f; // snow_layer
    case 79: return 0.5f; // ice
    case 80: return 0.2f; // snow
    case 81: return 0.4f; // cactus
    case 82: return 0.6f; // clay
    case 83: return 0.0f; // reeds
    case 84: return 2.0f; // jukebox
    case 85: return 2.0f; // fence
    case 86: return 1.0f; // pumpkin
    case 87: return 0.4f; // netherrack
    case 88: return 0.5f; // soul_sand
    case 89: return 0.3f; // glowstone
    case 90: return -1.0f; // portal
    case 91: return 1.0f; // lit_pumpkin
    case 92: return 0.5f; // cake
    case 93: return 0.0f; // unpowered_repeater
    case 94: return 0.0f; // powered_repeater
    case 95: return 0.3f; // stained_glass
    case 96: return 3.0f; // trapdoor
    case 97: return 0.75f; // monster_egg
    case 98: return 1.5f; // stonebrick
    case 99: return 0.0f; // brown_mushroom_block
    case 100: return 0.0f; // red_mushroom_block
    case 101: return 5.0f; // iron_bars
    case 102: return 0.3f; // glass_pane
    case 103: return 1.0f; // melon_block
    case 104: return 0.0f; // pumpkin_stem
    case 105: return 0.0f; // melon_stem
    case 106: return 0.2f; // vine
    case 107: return 2.0f; // fence_gate
    case 108: return 2.0f; // brick_stairs
    case 109: return 1.5f; // stone_brick_stairs
    case 110: return 0.6f; // mycelium
    case 111: return 0.6f; // waterlily
    case 112: return 2.0f; // nether_brick
    case 113: return 2.0f; // nether_brick_fence
    case 114: return 2.0f; // nether_brick_stairs
    case 115: return 0.0f; // nether_wart
    case 116: return 5.0f; // enchanting_table
    case 117: return 0.5f; // brewing_stand
    case 118: return 2.0f; // cauldron
    case 119: return -1.0f; // end_portal
    case 120: return -1.0f; // end_portal_frame
    case 121: return 3.0f; // end_stone
    case 122: return 3.0f; // dragon_egg
    case 123: return 0.3f; // redstone_lamp
    case 124: return 0.3f; // lit_redstone_lamp
    case 125: return 2.0f; // double_wooden_slab
    case 126: return 2.0f; // wooden_slab
    case 127: return 0.2f; // cocoa
    case 128: return 0.8f; // sandstone_stairs
    case 129: return 3.0f; // emerald_ore
    case 130: return 22.5f; // ender_chest
    case 131: return 0.0f; // tripwire_hook
    case 132: return 0.0f; // tripwire
    case 133: return 5.0f; // emerald_block
    case 134: return 2.0f; // spruce_stairs
    case 135: return 2.0f; // birch_stairs
    case 136: return 2.0f; // jungle_stairs
    case 137: return -1.0f; // command_block
    case 138: return 3.0f; // beacon
    case 139: return 2.0f; // cobblestone_wall
    case 140: return 0.0f; // flower_pot
    case 141: return 0.0f; // carrots
    case 142: return 0.0f; // potatoes
    case 143: return 0.5f; // wooden_button
    case 144: return 1.0f; // skull
    case 145: return 5.0f; // anvil
    case 146: return 2.5f; // trapped_chest
    case 147: return 0.5f; // light_weighted_pressure_plate
    case 148: return 0.5f; // heavy_weighted_pressure_plate
    case 149: return 0.0f; // unpowered_comparator
    case 150: return 0.0f; // powered_comparator
    case 151: return 0.2f; // daylight_detector
    case 152: return 5.0f; // redstone_block
    case 153: return 3.0f; // quartz_ore
    case 154: return 3.0f; // hopper
    case 155: return 0.8f; // quartz_block
    case 156: return 0.8f; // quartz_stairs
    case 157: return 0.7f; // activator_rail
    case 158: return 3.5f; // dropper
    case 159: return 1.25f; // stained_hardened_clay
    case 160: return 0.3f; // stained_glass_pane
    case 161: return 0.2f; // leaves2
    case 162: return 2.0f; // log2
    case 163: return 2.0f; // acacia_stairs
    case 164: return 2.0f; // dark_oak_stairs
    case 165: return 0.0f; // slime
    case 166: return -1.0f; // barrier
    case 167: return 5.0f; // iron_trapdoor
    case 168: return 1.5f; // prismarine
    case 169: return 0.3f; // sea_lantern
    case 170: return 0.5f; // hay_block
    case 171: return 0.1f; // carpet
    case 172: return 1.25f; // hardened_clay
    case 173: return 5.0f; // coal_block
    case 174: return 0.5f; // packed_ice
    case 175: return 0.0f; // double_plant
    case 176: return 1.0f; // standing_banner
    case 177: return 1.0f; // wall_banner
    case 178: return 0.2f; // daylight_detector_inverted
    case 179: return 0.8f; // red_sandstone
    case 180: return 0.8f; // red_sandstone_stairs
    case 181: return 2.0f; // double_stone_slab2
    case 182: return 2.0f; // stone_slab2
    case 183: return 2.0f; // spruce_fence_gate
    case 184: return 2.0f; // birch_fence_gate
    case 185: return 2.0f; // jungle_fence_gate
    case 186: return 2.0f; // dark_oak_fence_gate
    case 187: return 2.0f; // acacia_fence_gate
    case 188: return 2.0f; // spruce_fence
    case 189: return 2.0f; // birch_fence
    case 190: return 2.0f; // jungle_fence
    case 191: return 2.0f; // dark_oak_fence
    case 192: return 2.0f; // acacia_fence
    case 193: return 3.0f; // spruce_door
    case 194: return 3.0f; // birch_door
    case 195: return 3.0f; // jungle_door
    case 196: return 3.0f; // acacia_door
    case 197: return 3.0f; // dark_oak_door
    default: return 1.0f;
    }
}

uint8_t get_block_stack_size(uint16_t block_id) {
    switch(block_id) {
    case 0: return 0; // air
    case 1: return 64; // stone
    case 2: return 64; // grass
    case 3: return 64; // dirt
    case 4: return 64; // cobblestone
    case 5: return 64; // planks
    case 6: return 64; // sapling
    case 7: return 64; // bedrock
    case 8: return 64; // flowing_water
    case 9: return 64; // water
    case 10: return 64; // flowing_lava
    case 11: return 64; // lava
    case 12: return 64; // sand
    case 13: return 64; // gravel
    case 14: return 64; // gold_ore
    case 15: return 64; // iron_ore
    case 16: return 64; // coal_ore
    case 17: return 64; // log
    case 18: return 64; // leaves
    case 19: return 64; // sponge
    case 20: return 64; // glass
    case 21: return 64; // lapis_ore
    case 22: return 64; // lapis_block
    case 23: return 64; // dispenser
    case 24: return 64; // sandstone
    case 25: return 64; // noteblock
    case 26: return 1; // bed
    case 27: return 64; // golden_rail
    case 28: return 64; // detector_rail
    case 29: return 64; // sticky_piston
    case 30: return 64; // web
    case 31: return 64; // tallgrass
    case 32: return 64; // deadbush
    case 33: return 64; // piston
    case 34: return 0; // piston_head
    case 35: return 64; // wool
    case 36: return 0; // piston_extension
    case 37: return 64; // yellow_flower
    case 38: return 64; // red_flower
    case 39: return 64; // brown_mushroom
    case 40: return 64; // red_mushroom
    case 41: return 64; // gold_block
    case 42: return 64; // iron_block
    case 43: return 64; // double_stone_slab
    case 44: return 64; // stone_slab
    case 45: return 64; // brick_block
    case 46: return 64; // tnt
    case 47: return 64; // bookshelf
    case 48: return 64; // mossy_cobblestone
    case 49: return 64; // obsidian
    case 50: return 64; // torch
    case 51: return 0; // fire
    case 52: return 64; // mob_spawner
    case 53: return 64; // oak_stairs
    case 54: return 64; // chest
    case 55: return 64; // redstone_wire
    case 56: return 64; // diamond_ore
    case 57: return 64; // diamond_block
    case 58: return 64; // crafting_table
    case 59: return 64; // wheat
    case 60: return 64; // farmland
    case 61: return 64; // furnace
    case 62: return 64; // lit_furnace
    case 63: return 16; // standing_sign
    case 64: return 64; // wooden_door
    case 65: return 64; // ladder
    case 66: return 64; // rail
    case 67: return 64; // stone_stairs
    case 68: return 16; // wall_sign
    case 69: return 64; // lever
    case 70: return 64; // stone_pressure_plate
    case 71: return 64; // iron_door
    case 72: return 64; // wooden_pressure_plate
    case 73: return 64; // redstone_ore
    case 74: return 64; // lit_redstone_ore
    case 75: return 64; // unlit_redstone_torch
    case 76: return 64; // redstone_torch
    case 77: return 64; // stone_button
    case 78: return 64; // snow_layer
    case 79: return 64; // ice
    case 80: return 64; // snow
    case 81: return 64; // cactus
    case 82: return 64; // clay
    case 83: return 64; // reeds
    case 84: return 64; // jukebox
    case 85: return 64; // fence
    case 86: return 64; // pumpkin
    case 87: return 64; // netherrack
    case 88: return 64; // soul_sand
    case 89: return 64; // glowstone
    case 90: return 0; // portal
    case 91: return 64; // lit_pumpkin
    case 92: return 1; // cake
    case 93: return 64; // unpowered_repeater
    case 94: return 64; // powered_repeater
    case 95: return 64; // stained_glass
    case 96: return 64; // trapdoor
    case 97: return 64; // monster_egg
    case 98: return 64; // stonebrick
    case 99: return 64; // brown_mushroom_block
    case 100: return 64; // red_mushroom_block
    case 101: return 64; // iron_bars
    case 102: return 64; // glass_pane
    case 103: return 64; // melon_block
    case 104: return 64; // pumpkin_stem
    case 105: return 64; // melon_stem
    case 106: return 64; // vine
    case 107: return 64; // fence_gate
    case 108: return 64; // brick_stairs
    case 109: return 64; // stone_brick_stairs
    case 110: return 64; // mycelium
    case 111: return 64; // waterlily
    case 112: return 64; // nether_brick
    case 113: return 64; // nether_brick_fence
    case 114: return 64; // nether_brick_stairs
    case 115: return 64; // nether_wart
    case 116: return 64; // enchanting_table
    case 117: return 64; // brewing_stand
    case 118: return 64; // cauldron
    case 119: return 0; // end_portal
    case 120: return 64; // end_portal_frame
    case 121: return 64; // end_stone
    case 122: return 64; // dragon_egg
    case 123: return 64; // redstone_lamp
    case 124: return 64; // lit_redstone_lamp
    case 125: return 64; // double_wooden_slab
    case 126: return 64; // wooden_slab
    case 127: return 64; // cocoa
    case 128: return 64; // sandstone_stairs
    case 129: return 64; // emerald_ore
    case 130: return 64; // ender_chest
    case 131: return 64; // tripwire_hook
    case 132: return 64; // tripwire
    case 133: return 64; // emerald_block
    case 134: return 64; // spruce_stairs
    case 135: return 64; // birch_stairs
    case 136: return 64; // jungle_stairs
    case 137: return 64; // command_block
    case 138: return 64; // beacon
    case 139: return 64; // cobblestone_wall
    case 140: return 64; // flower_pot
    case 141: return 64; // carrots
    case 142: return 64; // potatoes
    case 143: return 64; // wooden_button
    case 144: return 64; // skull
    case 145: return 64; // anvil
    case 146: return 64; // trapped_chest
    case 147: return 64; // light_weighted_pressure_plate
    case 148: return 64; // heavy_weighted_pressure_plate
    case 149: return 64; // unpowered_comparator
    case 150: return 64; // powered_comparator
    case 151: return 64; // daylight_detector
    case 152: return 64; // redstone_block
    case 153: return 64; // quartz_ore
    case 154: return 64; // hopper
    case 155: return 64; // quartz_block
    case 156: return 64; // quartz_stairs
    case 157: return 64; // activator_rail
    case 158: return 64; // dropper
    case 159: return 64; // stained_hardened_clay
    case 160: return 64; // stained_glass_pane
    case 161: return 64; // leaves2
    case 162: return 64; // log2
    case 163: return 64; // acacia_stairs
    case 164: return 64; // dark_oak_stairs
    case 165: return 64; // slime
    case 166: return 64; // barrier
    case 167: return 64; // iron_trapdoor
    case 168: return 64; // prismarine
    case 169: return 64; // sea_lantern
    case 170: return 64; // hay_block
    case 171: return 64; // carpet
    case 172: return 64; // hardened_clay
    case 173: return 64; // coal_block
    case 174: return 64; // packed_ice
    case 175: return 64; // double_plant
    case 176: return 16; // standing_banner
    case 177: return 16; // wall_banner
    case 178: return 64; // daylight_detector_inverted
    case 179: return 64; // red_sandstone
    case 180: return 64; // red_sandstone_stairs
    case 181: return 64; // double_stone_slab2
    case 182: return 64; // stone_slab2
    case 183: return 64; // spruce_fence_gate
    case 184: return 64; // birch_fence_gate
    case 185: return 64; // jungle_fence_gate
    case 186: return 64; // dark_oak_fence_gate
    case 187: return 64; // acacia_fence_gate
    case 188: return 64; // spruce_fence
    case 189: return 64; // birch_fence
    case 190: return 64; // jungle_fence
    case 191: return 64; // dark_oak_fence
    case 192: return 64; // acacia_fence
    case 193: return 64; // spruce_door
    case 194: return 64; // birch_door
    case 195: return 64; // jungle_door
    case 196: return 64; // acacia_door
    case 197: return 64; // dark_oak_door
    default: return 64;
    }
}
